// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID        int64
	TrainerID int32
	UserID    int32
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Availability struct {
	ID        int32
	TrainerID int32
	Weekday   int16
	StartTime pgtype.Time
	EndTime   pgtype.Time
}

type Trainer struct {
	ID       int32
	Name     string
	Email    string
	Timezone string
}

type User struct {
	ID    int32
	Name  string
	Email string
}
