// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAppointment, id)
	return err
}

const getAppointmentsByTrainer = `-- name: GetAppointmentsByTrainer :many
SELECT
    a.id,
    a.starts_at,
    a.ends_at,
    a.created_at,
    t.id       AS trainer_id,
    t.name     AS trainer_name,
    t.timezone AS trainer_timezone,
    u.id       AS user_id,
    u.name     AS user_name
FROM appointments a
JOIN trainers t ON t.id = a.trainer_id
JOIN users    u ON u.id = a.user_id
WHERE a.trainer_id = $1
ORDER BY a.starts_at
`

type GetAppointmentsByTrainerRow struct {
	ID              int64
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	TrainerID       int32
	TrainerName     string
	TrainerTimezone string
	UserID          int32
	UserName        string
}

func (q *Queries) GetAppointmentsByTrainer(ctx context.Context, trainerID int32) ([]GetAppointmentsByTrainerRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByTrainer, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppointmentsByTrainerRow
	for rows.Next() {
		var i GetAppointmentsByTrainerRow
		if err := rows.Scan(
			&i.ID,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.TrainerID,
			&i.TrainerName,
			&i.TrainerTimezone,
			&i.UserID,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByTrainerBetween = `-- name: GetAppointmentsByTrainerBetween :many
SELECT id, trainer_id, user_id, starts_at, ends_at, created_at FROM appointments
WHERE trainer_id = $1
  AND starts_at >= $2
  AND ends_at   <= $3
ORDER BY starts_at
`

type GetAppointmentsByTrainerBetweenParams struct {
	TrainerID int32
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
}

func (q *Queries) GetAppointmentsByTrainerBetween(ctx context.Context, arg GetAppointmentsByTrainerBetweenParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointmentsByTrainerBetween, arg.TrainerID, arg.StartsAt, arg.EndsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.UserID,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailabilityByTrainer = `-- name: GetAvailabilityByTrainer :many
SELECT id, trainer_id, weekday, start_time, end_time FROM availability
WHERE trainer_id = $1
ORDER BY weekday, start_time
`

func (q *Queries) GetAvailabilityByTrainer(ctx context.Context, trainerID int32) ([]Availability, error) {
	rows, err := q.db.Query(ctx, getAvailabilityByTrainer, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Availability
	for rows.Next() {
		var i Availability
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailabilityByTrainerAndWeekday = `-- name: GetAvailabilityByTrainerAndWeekday :many
SELECT id, trainer_id, weekday, start_time, end_time FROM availability
WHERE trainer_id = $1 AND weekday = $2
ORDER BY start_time
`

type GetAvailabilityByTrainerAndWeekdayParams struct {
	TrainerID int32
	Weekday   int16
}

func (q *Queries) GetAvailabilityByTrainerAndWeekday(ctx context.Context, arg GetAvailabilityByTrainerAndWeekdayParams) ([]Availability, error) {
	rows, err := q.db.Query(ctx, getAvailabilityByTrainerAndWeekday, arg.TrainerID, arg.Weekday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Availability
	for rows.Next() {
		var i Availability
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverlappingAppointments = `-- name: GetOverlappingAppointments :many
SELECT id, trainer_id, user_id, starts_at, ends_at, created_at FROM appointments
WHERE trainer_id = $1
  AND starts_at < $2
  AND ends_at   > $3
`

type GetOverlappingAppointmentsParams struct {
	TrainerID int32
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
}

func (q *Queries) GetOverlappingAppointments(ctx context.Context, arg GetOverlappingAppointmentsParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getOverlappingAppointments, arg.TrainerID, arg.StartsAt, arg.EndsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.UserID,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainerByID = `-- name: GetTrainerByID :one
SELECT id, name, email, timezone FROM trainers WHERE id = $1
`

func (q *Queries) GetTrainerByID(ctx context.Context, id int32) (Trainer, error) {
	row := q.db.QueryRow(ctx, getTrainerByID, id)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Timezone,
	)
	return i, err
}

const insertAppointment = `-- name: InsertAppointment :one
INSERT INTO appointments (trainer_id, user_id, starts_at, ends_at)
VALUES ($1, $2, $3, $4)
RETURNING id, trainer_id, user_id, starts_at, ends_at, created_at
`

type InsertAppointmentParams struct {
	TrainerID int32
	UserID    int32
	StartsAt  pgtype.Timestamptz
	EndsAt    pgtype.Timestamptz
}

func (q *Queries) InsertAppointment(ctx context.Context, arg InsertAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, insertAppointment,
		arg.TrainerID,
		arg.UserID,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.UserID,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}
